//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GLAmountHistory
    {
        public long ID { get; set; }
        public string GLNumber { get; set; }
        public string TerminalID { get; set; }
        public string TerminalType { get; set; }
        public Nullable<System.DateTime> Transaction_TS { get; set; }
        public string TotalApproveAmount { get; set; }
        public string CountApproveTrans { get; set; }
        public Nullable<int> BotId { get; set; }
        public Nullable<System.DateTime> BotEntry_TS { get; set; }
    }
}
