//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankMuscat.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntitiesList : DbContext
    {
        public EntitiesList()
            : base("name=EntitiesList")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_BotMaster> tbl_BotMaster { get; set; }
        public virtual DbSet<tbl_DisputeData> tbl_DisputeData { get; set; }
        public virtual DbSet<tbl_EJData> tbl_EJData { get; set; }
        public virtual DbSet<tbl_EJLogsHistory> tbl_EJLogsHistory { get; set; }
        public virtual DbSet<tbl_GLAccountList> tbl_GLAccountList { get; set; }
        public virtual DbSet<tbl_GLAmountHistory> tbl_GLAmountHistory { get; set; }
        public virtual DbSet<tbl_MasterBINList> tbl_MasterBINList { get; set; }
        public virtual DbSet<tbl_MasterDeviceList> tbl_MasterDeviceList { get; set; }
        public virtual DbSet<tbl_MasterErrorCode> tbl_MasterErrorCode { get; set; }
    
        public virtual ObjectResult<GetDetailUserWise_Result> GetDetailUserWise(string input_type)
        {
            var input_typeParameter = input_type != null ?
                new ObjectParameter("input_type", input_type) :
                new ObjectParameter("input_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailUserWise_Result>("GetDetailUserWise", input_typeParameter);
        }
    
        public virtual ObjectResult<string> UDSP_GET_ErrorCode()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDSP_GET_ErrorCode");
        }
    
        public virtual ObjectResult<UDSP_GET_GLDETAILS_Result> UDSP_GET_GLDETAILS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDSP_GET_GLDETAILS_Result>("UDSP_GET_GLDETAILS");
        }
    
        public virtual ObjectResult<UDSP_GET_TERMINALLIST_Result> UDSP_GET_TERMINALLIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDSP_GET_TERMINALLIST_Result>("UDSP_GET_TERMINALLIST");
        }
    
        public virtual ObjectResult<Nullable<int>> UDSP_Insert_EJData(Nullable<int> param_countv, string param_AccountNumber, string param_CardNumber, string param_Amount, Nullable<System.DateTime> param_TransactionDate, string param_TerminalId, string param_DeviceId, string param_ErrorCode, string param_Currency_Code, string param_Counterfeit_Amount, string param_Cash_Retracted_Amount, string param_TransactionType, Nullable<System.DateTime> param_EntryTime, Nullable<int> param_BotIdEntry)
        {
            var param_countvParameter = param_countv.HasValue ?
                new ObjectParameter("Param_countv", param_countv) :
                new ObjectParameter("Param_countv", typeof(int));
    
            var param_AccountNumberParameter = param_AccountNumber != null ?
                new ObjectParameter("Param_AccountNumber", param_AccountNumber) :
                new ObjectParameter("Param_AccountNumber", typeof(string));
    
            var param_CardNumberParameter = param_CardNumber != null ?
                new ObjectParameter("Param_CardNumber", param_CardNumber) :
                new ObjectParameter("Param_CardNumber", typeof(string));
    
            var param_AmountParameter = param_Amount != null ?
                new ObjectParameter("Param_Amount", param_Amount) :
                new ObjectParameter("Param_Amount", typeof(string));
    
            var param_TransactionDateParameter = param_TransactionDate.HasValue ?
                new ObjectParameter("Param_TransactionDate", param_TransactionDate) :
                new ObjectParameter("Param_TransactionDate", typeof(System.DateTime));
    
            var param_TerminalIdParameter = param_TerminalId != null ?
                new ObjectParameter("Param_TerminalId", param_TerminalId) :
                new ObjectParameter("Param_TerminalId", typeof(string));
    
            var param_DeviceIdParameter = param_DeviceId != null ?
                new ObjectParameter("Param_DeviceId", param_DeviceId) :
                new ObjectParameter("Param_DeviceId", typeof(string));
    
            var param_ErrorCodeParameter = param_ErrorCode != null ?
                new ObjectParameter("Param_ErrorCode", param_ErrorCode) :
                new ObjectParameter("Param_ErrorCode", typeof(string));
    
            var param_Currency_CodeParameter = param_Currency_Code != null ?
                new ObjectParameter("Param_Currency_Code", param_Currency_Code) :
                new ObjectParameter("Param_Currency_Code", typeof(string));
    
            var param_Counterfeit_AmountParameter = param_Counterfeit_Amount != null ?
                new ObjectParameter("Param_Counterfeit_Amount", param_Counterfeit_Amount) :
                new ObjectParameter("Param_Counterfeit_Amount", typeof(string));
    
            var param_Cash_Retracted_AmountParameter = param_Cash_Retracted_Amount != null ?
                new ObjectParameter("Param_Cash_Retracted_Amount", param_Cash_Retracted_Amount) :
                new ObjectParameter("Param_Cash_Retracted_Amount", typeof(string));
    
            var param_TransactionTypeParameter = param_TransactionType != null ?
                new ObjectParameter("Param_TransactionType", param_TransactionType) :
                new ObjectParameter("Param_TransactionType", typeof(string));
    
            var param_EntryTimeParameter = param_EntryTime.HasValue ?
                new ObjectParameter("Param_EntryTime", param_EntryTime) :
                new ObjectParameter("Param_EntryTime", typeof(System.DateTime));
    
            var param_BotIdEntryParameter = param_BotIdEntry.HasValue ?
                new ObjectParameter("Param_BotIdEntry", param_BotIdEntry) :
                new ObjectParameter("Param_BotIdEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDSP_Insert_EJData", param_countvParameter, param_AccountNumberParameter, param_CardNumberParameter, param_AmountParameter, param_TransactionDateParameter, param_TerminalIdParameter, param_DeviceIdParameter, param_ErrorCodeParameter, param_Currency_CodeParameter, param_Counterfeit_AmountParameter, param_Cash_Retracted_AmountParameter, param_TransactionTypeParameter, param_EntryTimeParameter, param_BotIdEntryParameter);
        }
    
        public virtual int UDSP_INSERT_EJLogsHistory(string param_TerminalID, string param_DeviceId, Nullable<System.DateTime> param_Transaction_TS, string param_TransactionType, Nullable<int> param_BotId, Nullable<System.DateTime> param_BotEntry_TS, string param_TotalAmount, string param_CountTotalTrans, string param_TotalApproveAmount, string param_CountApproveTrans, string param_TotalErroneousAmount, string param_CountErroneousTrans)
        {
            var param_TerminalIDParameter = param_TerminalID != null ?
                new ObjectParameter("Param_TerminalID", param_TerminalID) :
                new ObjectParameter("Param_TerminalID", typeof(string));
    
            var param_DeviceIdParameter = param_DeviceId != null ?
                new ObjectParameter("Param_DeviceId", param_DeviceId) :
                new ObjectParameter("Param_DeviceId", typeof(string));
    
            var param_Transaction_TSParameter = param_Transaction_TS.HasValue ?
                new ObjectParameter("Param_Transaction_TS", param_Transaction_TS) :
                new ObjectParameter("Param_Transaction_TS", typeof(System.DateTime));
    
            var param_TransactionTypeParameter = param_TransactionType != null ?
                new ObjectParameter("Param_TransactionType", param_TransactionType) :
                new ObjectParameter("Param_TransactionType", typeof(string));
    
            var param_BotIdParameter = param_BotId.HasValue ?
                new ObjectParameter("Param_BotId", param_BotId) :
                new ObjectParameter("Param_BotId", typeof(int));
    
            var param_BotEntry_TSParameter = param_BotEntry_TS.HasValue ?
                new ObjectParameter("Param_BotEntry_TS", param_BotEntry_TS) :
                new ObjectParameter("Param_BotEntry_TS", typeof(System.DateTime));
    
            var param_TotalAmountParameter = param_TotalAmount != null ?
                new ObjectParameter("Param_TotalAmount", param_TotalAmount) :
                new ObjectParameter("Param_TotalAmount", typeof(string));
    
            var param_CountTotalTransParameter = param_CountTotalTrans != null ?
                new ObjectParameter("Param_CountTotalTrans", param_CountTotalTrans) :
                new ObjectParameter("Param_CountTotalTrans", typeof(string));
    
            var param_TotalApproveAmountParameter = param_TotalApproveAmount != null ?
                new ObjectParameter("Param_TotalApproveAmount", param_TotalApproveAmount) :
                new ObjectParameter("Param_TotalApproveAmount", typeof(string));
    
            var param_CountApproveTransParameter = param_CountApproveTrans != null ?
                new ObjectParameter("Param_CountApproveTrans", param_CountApproveTrans) :
                new ObjectParameter("Param_CountApproveTrans", typeof(string));
    
            var param_TotalErroneousAmountParameter = param_TotalErroneousAmount != null ?
                new ObjectParameter("Param_TotalErroneousAmount", param_TotalErroneousAmount) :
                new ObjectParameter("Param_TotalErroneousAmount", typeof(string));
    
            var param_CountErroneousTransParameter = param_CountErroneousTrans != null ?
                new ObjectParameter("Param_CountErroneousTrans", param_CountErroneousTrans) :
                new ObjectParameter("Param_CountErroneousTrans", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDSP_INSERT_EJLogsHistory", param_TerminalIDParameter, param_DeviceIdParameter, param_Transaction_TSParameter, param_TransactionTypeParameter, param_BotIdParameter, param_BotEntry_TSParameter, param_TotalAmountParameter, param_CountTotalTransParameter, param_TotalApproveAmountParameter, param_CountApproveTransParameter, param_TotalErroneousAmountParameter, param_CountErroneousTransParameter);
        }
    
        public virtual int UDSP_INSERT_GLAmountHistory(string param_GLNumber, string param_TerminalId, string param_TerminalType, Nullable<System.DateTime> param_Transaction_TS, string param_TotalApproveAmount, string param_CountApproveTrans, Nullable<int> param_BotId, Nullable<System.DateTime> botEntry_TS)
        {
            var param_GLNumberParameter = param_GLNumber != null ?
                new ObjectParameter("Param_GLNumber", param_GLNumber) :
                new ObjectParameter("Param_GLNumber", typeof(string));
    
            var param_TerminalIdParameter = param_TerminalId != null ?
                new ObjectParameter("Param_TerminalId", param_TerminalId) :
                new ObjectParameter("Param_TerminalId", typeof(string));
    
            var param_TerminalTypeParameter = param_TerminalType != null ?
                new ObjectParameter("Param_TerminalType", param_TerminalType) :
                new ObjectParameter("Param_TerminalType", typeof(string));
    
            var param_Transaction_TSParameter = param_Transaction_TS.HasValue ?
                new ObjectParameter("Param_Transaction_TS", param_Transaction_TS) :
                new ObjectParameter("Param_Transaction_TS", typeof(System.DateTime));
    
            var param_TotalApproveAmountParameter = param_TotalApproveAmount != null ?
                new ObjectParameter("Param_TotalApproveAmount", param_TotalApproveAmount) :
                new ObjectParameter("Param_TotalApproveAmount", typeof(string));
    
            var param_CountApproveTransParameter = param_CountApproveTrans != null ?
                new ObjectParameter("Param_CountApproveTrans", param_CountApproveTrans) :
                new ObjectParameter("Param_CountApproveTrans", typeof(string));
    
            var param_BotIdParameter = param_BotId.HasValue ?
                new ObjectParameter("Param_BotId", param_BotId) :
                new ObjectParameter("Param_BotId", typeof(int));
    
            var botEntry_TSParameter = botEntry_TS.HasValue ?
                new ObjectParameter("BotEntry_TS", botEntry_TS) :
                new ObjectParameter("BotEntry_TS", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDSP_INSERT_GLAmountHistory", param_GLNumberParameter, param_TerminalIdParameter, param_TerminalTypeParameter, param_Transaction_TSParameter, param_TotalApproveAmountParameter, param_CountApproveTransParameter, param_BotIdParameter, botEntry_TSParameter);
        }
    
        public virtual ObjectResult<string> UDSP_SEARCH_TotalApproveAmount(string param_TerminalId, string param_TerminalType, Nullable<System.DateTime> param_Transaction_TS)
        {
            var param_TerminalIdParameter = param_TerminalId != null ?
                new ObjectParameter("Param_TerminalId", param_TerminalId) :
                new ObjectParameter("Param_TerminalId", typeof(string));
    
            var param_TerminalTypeParameter = param_TerminalType != null ?
                new ObjectParameter("Param_TerminalType", param_TerminalType) :
                new ObjectParameter("Param_TerminalType", typeof(string));
    
            var param_Transaction_TSParameter = param_Transaction_TS.HasValue ?
                new ObjectParameter("Param_Transaction_TS", param_Transaction_TS) :
                new ObjectParameter("Param_Transaction_TS", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDSP_SEARCH_TotalApproveAmount", param_TerminalIdParameter, param_TerminalTypeParameter, param_Transaction_TSParameter);
        }
    
        public virtual int UDSP_UPDATE_BalancingAmount(string param_TerminalID, string param_BalancingAmount, Nullable<System.DateTime> param_BotEntry_TS, string param_TransactionType)
        {
            var param_TerminalIDParameter = param_TerminalID != null ?
                new ObjectParameter("Param_TerminalID", param_TerminalID) :
                new ObjectParameter("Param_TerminalID", typeof(string));
    
            var param_BalancingAmountParameter = param_BalancingAmount != null ?
                new ObjectParameter("Param_BalancingAmount", param_BalancingAmount) :
                new ObjectParameter("Param_BalancingAmount", typeof(string));
    
            var param_BotEntry_TSParameter = param_BotEntry_TS.HasValue ?
                new ObjectParameter("Param_BotEntry_TS", param_BotEntry_TS) :
                new ObjectParameter("Param_BotEntry_TS", typeof(System.DateTime));
    
            var param_TransactionTypeParameter = param_TransactionType != null ?
                new ObjectParameter("Param_TransactionType", param_TransactionType) :
                new ObjectParameter("Param_TransactionType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDSP_UPDATE_BalancingAmount", param_TerminalIDParameter, param_BalancingAmountParameter, param_BotEntry_TSParameter, param_TransactionTypeParameter);
        }
    }
}
